version: "3.9"

services:
  frontend:
    build: ./frontend
    image: e-commerce_front:latest
    container_name: e-commerce_front
    ports:
      - "3000:3000"
    working_dir: /app
    command: npm start
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    build: ./backend
    image: e-commerce_back:latest
    container_name: e-commerce_back
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app

  nginx:
    image: nginx:latest
    container_name: e-commerce_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"